In [1]:
pdf_bernoulli(p,t) = p^t * (1-p)^(1-t)

function EM_bernoulli(t, m,μ)
    P=size(t,1)
    N=size(t,2)
    G=length(m)
    
    τ=zeros(N,G)
    for g=1:G, n=1:N; τ[n,g] = m[g] * prod([pdf_bernoulli(μ[p,g], t[p,n]) for p=1:P]); end
    τ = τ./sum(τ,2)

    T1=sum(τ,1)
    T2 = t*τ
    m = (T1./N)'
    μ = T2./T1
    return m,μ
end

function some_data(P,N)
    n=Int(N/6)
    
    t1=[1,1,0,0,0] * ones(n)'
    t2=[0,0,1,1,0] * ones(n)'
    
    t3=[1,0,0,1,0] * ones(n)'
    t4=[0,1,1,0,0] * ones(n)'
    
    t5=[1,1,1,0,1] * ones(n)'
    t6=[0,0,1,1,1] * ones(n)'
    
    t=hcat(t1,t2,t3,t4,t5,t6)
    return t
end

some_data (generic function with 1 method)

In [2]:
G=6 #nr of components
N=60 #nr of samples
P=5 #dimensionality of data
t=some_data(P,N)

m=ones(G)/G
μ=rand(P,G)
for ITER=1:1000
    m,μ = EM_bernoulli(t, m,μ)
end

#Component mixing proportions and component μ's
println(round.(m',2))
round.(μ,2)

[0.17 0.17 0.21 0.17 0.17 0.13]


5×6 Array{Float64,2}:
 1.0  1.0  0.0   1.0  0.0  0.0 
 1.0  1.0  0.0   0.0  1.0  0.0 
 0.0  1.0  1.0   0.0  1.0  1.0 
 0.0  0.0  1.0   1.0  0.0  1.0 
 0.0  1.0  0.58  0.0  0.0  0.36

In [3]:
#estimated expectation and covariance of data:
E = sum(μ.*m',2) #real: mean(t,2)
Σ = sum([m[g] * (diagm(μ[:,g].*(1-μ[:,g])) + μ[:,g]*μ[:,g]') for g=1:G]) - E*E' #real: cov(t')

5×5 Array{Float64,2}:
  0.25          0.0833333    -0.166667     -0.0833333    -2.77556e-17
  0.0833333     0.25         -5.55112e-17  -0.25         -2.77556e-17
 -0.166667     -5.55112e-17   0.222222      5.55112e-17   0.111111   
 -0.0833333    -0.25          5.55112e-17   0.25          0.0        
 -2.77556e-17  -2.77556e-17   0.111111      0.0           0.222222   